### ISSUE TITLE
Why is there no icon like yours in the upper right corner of my game details interface?

### ISSUE THREAD

**Issue by Warm-boy123** [sakasakiking/Dune#1]
As shown in the figure:
![image](https://github.com/user-attachments/assets/144906fa-8b75-4a6f-b78f-910baf623a38)

**Comment by Warm-boy123** [comment]
Solved, the reason is that I didn't download the additional extension: Logos: [Extra Metadata Loader](https://playnite.link/addons.html#ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429) extension.

**Comment by sakasakiking** [comment]
很高兴你找到了解决方法。实际上，这里如果没有使用这个插件的话，会显示游戏本身的icon，如果连icon也没有则会显示主题的默认游戏icon，不会是空白。
![image](https://github.com/user-attachments/assets/aeabf671-d262-41ee-8f5a-3d0388db6592)
最后，感谢使用主题。
